package com.favedish.presentation.dishdetails.destination

import com.favedish.presentation.architecture.model.PresentationDestination

sealed interface DishDetailsPresentationDestination : PresentationDestination
